version: '3.3'
networks:
  default:

services:
  web:
    container_name: stocks
    build: .
    image: stocks-crawler
    ports:
      - 5000:5000
    env_file:
       - .env
    depends_on:
      - mongo

  mongo:
    container_name: mongo_stocks
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
